packages:
  - 'restale-kit'
  - 'examples/express-and-react-query/client'
  - 'examples/express-and-react-query/server'
  - 'examples/express-and-react-query/shared'

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - helmet@8.3.0
