import {
  type InvalidateSignal,
  type ChannelState,
  type EventStore,
  type SignalTarget,
  type LifetimeOptions,
  type BeforeFrameFn,
  type FrameGuardCtx,
  type FrameGuardResult,
} from '@/types/protocol.js'
import { ChannelClosedError } from '@/types/errors.js'
import {
  formatInvalidateFrame,
  formatKeepalive,
  formatRevokeFrame,
  formatRetryFrame,
  formatRenewFrame,
} from '@/server/core/framing.js'
import { createEventStore } from '@/server/core/event-store.js'
import { PROTOCOL_CONSTANTS, FRAME_GUARD_DEFAULTS } from '@/utils/constants.js'

/**
 * Configuration options for `createSSEChannel`.
 */
export interface SSEChannelOptions {
  /** Target discriminator or target array for automatic signal tagging and multi-target fanout. Required unless provided via group channelDefaults. */
  target?: SignalTarget | SignalTarget[]
  /** Keepalive comment interval in milliseconds. Default: 0 (disabled). */
  keepaliveIntervalMs?: number
  /** Optional retry interval in milliseconds to send as a `retry: <ms>` frame on stream start. */
  retryIntervalMs?: number
  /** Last event ID received from the client (e.g. from standard Last-Event-ID HTTP header). */
  lastEventId?: string
  /** Shared EventStore for recording history and replaying missed events upon reconnect. */
  eventStore?: EventStore
  /** Capacity of automatically instantiated EventStore if `eventStore` is not provided. Defaults to 50 when `lifetime` options are set without an explicit `eventStore` or capacity. */
  eventBufferCapacity?: number
  /** Custom ID generator for assigned event frames. Ignored if an external `eventStore` is provided. */
  idGenerator?: () => string
  /**
   * The unique connection ID generated by the client and sent as `__restale_cid__`.
   * Transport adapters (`attachSSE`, `toSSEResponse`) extract this from the request URL
   * and pass it here automatically.
   *
   * You may set this manually in tests or when calling `createSSEChannel` directly
   * without a transport adapter. In production code routed through a transport adapter,
   * the adapter always supplies this value — leave it unset.
   */
  connectionId?: string
  /**
   * The single target requested by the client, extracted from the `__restale_target__`
   * query parameter by transport adapters. When set, the channel will:
   * - Reject the connection immediately if the requested target is not in `options.target`.
   * - Filter outgoing frames to only emit signals matching this target.
   *
   * Accepts any string (not just known `SignalTarget` values) so that unrecognized
   * targets sent by the client are passed through and rejected by the unsupported-target
   * check rather than silently treated as "no preference".
   */
  requestedTarget?: string
  /**
   * A connection-level deadline after which the channel is closed.
   *
   * Express either as a relative duration from connection start (`ttlMs`) or as an
   * absolute epoch-ms timestamp (`deadline`). The two are mutually exclusive.
   *
   * When the deadline fires, `onDeadline` (default `'reconnect'`) controls whether the
   * channel sends a `renew` frame (asking the client to make one confirmatory reconnect
   * through the real auth middleware) or a terminal `revoke` frame.
   */
  lifetime?: LifetimeOptions
  /**
   * Integrator-supplied guard function called synchronously before each outgoing frame.
   *
   * By default it runs before **signal frames only**. Set `guardKeepalive: true` to also
   * run it before every keepalive tick (opt-in because keepalives are high-frequency).
   *
   * The function must be synchronous. Errors thrown inside it are the integrator's
   * responsibility — an unhandled throw is treated as `{ action: 'close' }`.
   */
  beforeFrame?: BeforeFrameFn<InvalidateSignal>
  /**
   * When `true`, `beforeFrame` also runs before every keepalive tick.
   * Has no effect if `beforeFrame` is not set. Default: `false`.
   */
  guardKeepalive?: boolean
}

/**
 * A server-side SSE channel that produces a `ReadableStream<Uint8Array>`.
 *
 * Runtime-agnostic — does not know about Node's `http` module or any specific
 * framework. Transport helpers (`restale-kit/node`, `restale-kit/fetch`) pipe
 * this stream into their runtime's response mechanism.
 */
export interface SSEChannel<TSignal extends InvalidateSignal = InvalidateSignal> {
  /** Current lifecycle state of the channel. */
  readonly state: ChannelState
  /**
   * The unique connection ID sent by the client (`__restale_cid__`).
   * Use this to register connection-level metadata and support targeted revocation
   * (e.g. close a specific tab's connection on logout).
   */
  readonly connectionId: string
  /** Configured target discriminator or target array. Required. */
  readonly target: SignalTarget | SignalTarget[]
  /** The single target requested by this client via query param, if any. May be an unrecognized string if the client sent an unknown target. */
  readonly requestedTarget: string | undefined
  /** The SSE byte stream to pipe into a response. */
  readonly stream: ReadableStream<Uint8Array>
  /**
   * Enqueue an invalidation signal (or batch) into the stream.
   *
   * - When `state` is `'closed'`: throws `ChannelClosedError`.
   *
   * Returns the event ID assigned to the invalidation frame.
   */
  invalidate(signal: TSignal | TSignal[] | InvalidateSignal | InvalidateSignal[], customId?: string): string
  /** Server-initiated close. Stops keepalive timer, closes the stream, transitions to `'closed'`. Idempotent. */
  close(): void
  /**
   * Called by a transport adapter when it detects the remote peer disconnected.
   * Same effect as `close()`. Idempotent.
   */
  disconnect(): void
  /**
   * Sends a terminal `revoke` SSE event frame to the client and then closes the channel.
   *
   * The client uses this event to distinguish an intentional server-initiated revocation
   * (logout, session expiry, security kick) from a transient network error, and will
   * NOT automatically reconnect. The resulting client status is `{ status: 'closed', reason: 'revoked' }`.
   *
   * Idempotent — if the channel is already closed, this is a no-op.
   *
   * @param reason - Human-readable reason string included in the event payload. Default: `'revoked'`.
   */
  revoke(reason?: string): void
  /**
   * Registers a one-shot callback invoked when the channel transitions to `'closed'`
   * (whether via `close()`, `disconnect()`, `revoke()`, or stream cancellation).
   * If the channel is already closed the callback fires synchronously.
   */
  onClose(callback: () => void): void
}

/**
 * Creates a new SSE channel.
 *
 * The channel produces a standard `ReadableStream<Uint8Array>` containing
 * SSE-formatted events and periodic keepalive comments. Transport adapters
 * pipe this stream into a response.
 */
export function createSSEChannel<TSignal extends InvalidateSignal = InvalidateSignal>(
  options: SSEChannelOptions
): SSEChannel<TSignal> {
  if (options.target === undefined) {
    throw new Error('[createSSEChannel] target is required.')
  }
  const target = options.target
  const keepaliveIntervalMs =
    options.keepaliveIntervalMs ?? PROTOCOL_CONSTANTS.DEFAULT_KEEPALIVE_INTERVAL_MS
  const retryIntervalMs = options.retryIntervalMs
  const lastEventId = options.lastEventId
  const idGenerator = options.idGenerator
  const connectionId = options.connectionId ?? ''
  const requestedTarget = options.requestedTarget
  const beforeFrame = options.beforeFrame
  const guardKeepalive = options.guardKeepalive ?? false
  // True if the client provided a Last-Event-ID header — i.e. this is a reconnect.
  const isResume = lastEventId !== undefined

  // Auto-allocate default buffer capacity when lifetime deadline renewal is set without an eventStore
  const effectiveBufferCapacity =
    options.eventBufferCapacity ??
    (options.eventStore === undefined && options.lifetime !== undefined ? 50 : undefined)

  // Track whether this channel owns its eventStore (created internally) or was given an
  // external one. When the store is external (shared with a group), the group is responsible
  // for recording signals before calling invalidate() with a customId — the channel must not
  // call eventStore.add() a second time for the same event.
  const eventStore =
    options.eventStore ??
    (effectiveBufferCapacity !== undefined && effectiveBufferCapacity > 0
      ? createEventStore({ capacity: effectiveBufferCapacity, idGenerator })
      : undefined)
  const ownsEventStore = options.eventStore === undefined

  let state: ChannelState = 'open'
  let controller: ReadableStreamDefaultController<Uint8Array>
  let keepaliveTimer: ReturnType<typeof setInterval> | undefined
  let lifetimeTimer: ReturnType<typeof setTimeout> | undefined
  const closeCallbacks: Array<() => void> = []

  // ── Lifetime timer helpers ────────────────────────────────────────────────

  function resolveLifetimeMs(connectedAt: number): number | undefined {
    if (options.lifetime === undefined) return undefined
    const { ttlMs, deadline } = options.lifetime
    if (ttlMs !== undefined) return ttlMs
    if (deadline === undefined) return undefined  
    return deadline - connectedAt
  }

  function scheduleLifetimeTimer(connectedAt: number): void {
    const rawDelayMs = resolveLifetimeMs(connectedAt)
    if (rawDelayMs === undefined) return

    // Apply jitter so connections sharing the same TTL don't all send renew simultaneously.
    const jitter = Math.random() * FRAME_GUARD_DEFAULTS.DEADLINE_JITTER_WINDOW_MS

    // Enforce the minimum-fire floor: even a deadline already in the past must not fire
    // immediately — it must wait at least DEADLINE_MIN_FIRE_DELAY_MS (spec §4.1.6).
    const fireDelayMs = Math.max(
      FRAME_GUARD_DEFAULTS.DEADLINE_MIN_FIRE_DELAY_MS,
      rawDelayMs + jitter
    )

    lifetimeTimer = setTimeout(() => {
      lifetimeTimer = undefined
      if (state !== 'open') return
      fireDeadline()
    }, fireDelayMs)
  }

  function fireDeadline(): void {
    if (state !== 'open') return

    const onDeadline = options.lifetime?.onDeadline ?? 'reconnect'

    if (onDeadline === 'revoke') {
      channelObj.revoke('deadline')
      return
    }

    // 'reconnect' (default) or object form — resolve maxAttempts / retryDelayMs.
    const maxAttempts =
      typeof onDeadline === 'object'
        ? (onDeadline.maxAttempts ?? FRAME_GUARD_DEFAULTS.RENEW_MAX_ATTEMPTS)
        : FRAME_GUARD_DEFAULTS.RENEW_MAX_ATTEMPTS
    const retryDelayMs =
      typeof onDeadline === 'object'
        ? (onDeadline.retryDelayMs ?? FRAME_GUARD_DEFAULTS.RENEW_RETRY_DELAY_MS)
        : FRAME_GUARD_DEFAULTS.RENEW_RETRY_DELAY_MS

    try {
      controller.enqueue(formatRenewFrame(maxAttempts, retryDelayMs))
    } catch {
      // controller already unusable — just close without the frame
    }
    closeInternal()
  }

  // ── Frame guard helper ────────────────────────────────────────────────────

  /**
   * Runs `beforeFrame` if it is configured for the given frame type.
   * Returns the result, or `{ action: 'send' }` when no guard is configured.
   * A thrown error inside `beforeFrame` is treated as `{ action: 'close' }` (spec §6).
   */
  function runGuard(ctx: FrameGuardCtx<TSignal>): FrameGuardResult {
    if (beforeFrame === undefined) return { action: 'send' }
    if (ctx.frameType === 'keepalive' && !guardKeepalive) return { action: 'send' }
    try {
      return beforeFrame(ctx)
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      console.warn(
        '[WARN][createSSEChannel] beforeFrame threw an unhandled error — treating as { action: \'close\' }.',
        '\n  error:', error.stack || error.message
      )
      return { action: 'close' }
    }
  }

  // ── Stream ────────────────────────────────────────────────────────────────

  const stream = new ReadableStream<Uint8Array>({
    start(ctrl) {
      controller = ctrl
      const connectedAt = Date.now()

      // Validate the requested target before doing anything else.
      // If it is unsupported or missing on a multi-target channel, emit a structured revoke frame and close immediately.
      const supportedTargets = Array.isArray(target) ? target : [target]
      if (requestedTarget === undefined && supportedTargets.length > 1) {
        const safeConnectionId = connectionId.replace(/\r\n|\r|\n/g, '\\n')
        console.warn(
          `[WARN][createSSEChannel] Rejected connection: no target requested for multi-target channel [${supportedTargets.join(', ')}]. connectionId: ${safeConnectionId}.`
        )
        try {
          controller.enqueue(
            formatRevokeFrame('unsupported-target', {
              requested: '',
              supported: supportedTargets,
            })
          )
        } catch {
          // controller unusable — just close
        }
        closeInternal()
        return
      }

      if (requestedTarget !== undefined) {
        // @ts-expect-error includes not present for SignalTarget type
        if (!supportedTargets.includes(requestedTarget)) {
          const safeRequestedTarget = requestedTarget.replace(/\r\n|\r|\n/g, '\\n')
          const safeConnectionId = connectionId.replace(/\r\n|\r|\n/g, '\\n')
          console.warn(
            `[WARN][createSSEChannel] Rejected connection: requested target "${safeRequestedTarget}" not in supported set [${supportedTargets.join(', ')}]. connectionId: ${safeConnectionId}.`
          )
          try {
            controller.enqueue(
              formatRevokeFrame('unsupported-target', {
                requested: requestedTarget,
                supported: supportedTargets,
              })
            )
          } catch {
            // controller unusable — just close
          }
          closeInternal()
          return
        }
      }

      if (retryIntervalMs !== undefined) {
        try {
          controller.enqueue(formatRetryFrame(retryIntervalMs))
        } catch {
          closeInternal()
          return
        }
      }

      // Replay missed historical events if lastEventId and eventStore are present
      if (lastEventId !== undefined && eventStore !== undefined) {
        try {
          const { events: missed, stale } = eventStore.getEventsAfter(lastEventId)
          if (stale) {
            // The cursor fell off the ring buffer or was never valid — the client missed
            // an unknown number of events. Send a full-invalidate signal (key: []) so the
            // client refetches everything rather than silently displaying stale data.
            const declaredList = Array.isArray(target) ? target : [target]
            const foundTarget = declaredList.find((t) => t === requestedTarget)
            const staleTarget: SignalTarget = foundTarget ?? declaredList[0] ?? 'generic'
            const staleSignal: InvalidateSignal =
              staleTarget === 'tanstack-query'
                ? { target: 'tanstack-query', queryKey: [] }
                : staleTarget === 'swr'
                  ? { target: 'swr', key: [] }
                  : staleTarget === 'rtk-query'
                    ? { target: 'rtk-query', tags: [] }
                    : { target: 'generic', key: [] }
            controller.enqueue(formatInvalidateFrame(staleSignal))
          } else {
            for (const record of missed) {
              const replaySignal = record.signal

              // Apply requestedTarget filter: skip signals that don't match this client's
              // requested target (same semantics as the live invalidate() filter path).
              if (requestedTarget !== undefined) {
                if (Array.isArray(replaySignal)) {
                  const filtered = replaySignal.filter((s) => {
                    const t = 'target' in s ? s.target : undefined
                    return t === requestedTarget
                  })
                  if (filtered.length === 0) continue
                  controller.enqueue(formatInvalidateFrame(filtered, record.id))
                  continue
                } else {
                  const t = 'target' in replaySignal ? replaySignal.target : undefined
                  if (t !== requestedTarget) continue
                }
              }

              controller.enqueue(formatInvalidateFrame(replaySignal, record.id))
            }
          }
        } catch {
          closeInternal()
          return
        }
      }

      if (keepaliveIntervalMs > 0) {
        keepaliveTimer = setInterval(() => {
          if (state !== 'open') return

          // Run the guard before every keepalive tick when guardKeepalive is enabled.
          if (beforeFrame !== undefined && guardKeepalive) {
            const ctx: FrameGuardCtx<InvalidateSignal> = {
              signal: undefined,
              frameType: 'keepalive',
              connectionId,
              requestedTarget,
              isResume,
            }
            const result = runGuard(ctx)
            if (result.action === 'skip') return
            if (result.action === 'close') {
              channelObj.revoke(result.reason)
              return
            }
          }

          try {
            controller.enqueue(formatKeepalive())
          } catch {
            closeInternal()
          }
        }, keepaliveIntervalMs)
      }

      scheduleLifetimeTimer(connectedAt)
    },
    cancel() {
      // Stream consumer cancelled — treat as disconnect
      closeInternal()
    },
  })

  // ── closeInternal ─────────────────────────────────────────────────────────

  function closeInternal(): void {
    if (state === 'closed') return
    state = 'closed'
    if (keepaliveTimer !== undefined) {
      clearInterval(keepaliveTimer)
      keepaliveTimer = undefined
    }
    if (lifetimeTimer !== undefined) {
      clearTimeout(lifetimeTimer)
      lifetimeTimer = undefined
    }
    try {
      controller.close()
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      // The stream controller closed status during cleanup
      console.warn(
        "[WARN][closeInternal] Controller close threw an expected error (likely already closed)",
        "\n  error:", error.stack || error.message
      )
    }
    // Fire one-shot close callbacks
    for (const cb of closeCallbacks) {
      try { cb() } catch { /* ignore errors in close callbacks */ }
    }
    closeCallbacks.length = 0
  }

  // ── invalidate ────────────────────────────────────────────────────────────

  function invalidate(
    signal: TSignal | TSignal[] | InvalidateSignal | InvalidateSignal[],
    customId?: string
  ): string {
    if (state === 'closed') {
      throw new ChannelClosedError()
    }

    validateSignalTargets(signal, target)

    const effectiveSignal = signal

    // Filter by requestedTarget: drop signals that don't match the client's requested target.
    if (requestedTarget !== undefined) {
      if (Array.isArray(effectiveSignal)) {
        const filtered = effectiveSignal.filter((s) => {
          const t = 'target' in s ? s.target : undefined
          const keep = t === requestedTarget
          return keep
        })
        if (filtered.length === 0) return ''
        // Re-assign and continue with the filtered batch
        return invalidateFiltered(filtered, customId)
      } else {
        const t = 'target' in effectiveSignal ? effectiveSignal.target : undefined
        if (t !== requestedTarget) {
          return ''
        }
      }
    }

    return invalidateFiltered(effectiveSignal, customId)
  }

  function invalidateFiltered(
    effectiveSignal: InvalidateSignal | InvalidateSignal[],
    customId?: string
  ): string {
    // Run the frame guard before the signal frame is enqueued.
    if (beforeFrame !== undefined) {
      const ctx: FrameGuardCtx<TSignal> = {
        // @ts-expect-error am tired of fighting this error
        signal: effectiveSignal,
        frameType: 'signal',
        connectionId,
        requestedTarget,
        isResume,
      }
      const result = runGuard(ctx)
      if (result.action === 'skip') return ''
      if (result.action === 'close') {
        channelObj.revoke(result.reason)
        throw new ChannelClosedError()
      }
      // result.action === 'send' — fall through
    }

    let eventId = customId
    if (eventId === undefined && idGenerator !== undefined) {
      eventId = idGenerator()
    }

    if (eventStore !== undefined) {
      if (ownsEventStore || customId === undefined) {
        // Channel owns its store, or no id was provided — record it now.
        const record = eventStore.add(effectiveSignal, eventId)
        eventId = record.id
      } else {
        // External store with a customId provided: only skip add() when the record already
        // exists (i.e. the group pre-recorded it). If it is absent (standalone usage or an
        // unexpected call order), fall back to add() so the event is not silently lost.
        const { stale } = eventStore.getEventsAfter(customId)
        const alreadyRecorded = !stale
        if (!alreadyRecorded) {
          const record = eventStore.add(effectiveSignal, customId)
          eventId = record.id
        }
      }
    }

    try {
      controller.enqueue(formatInvalidateFrame(effectiveSignal, eventId))
    } catch {
      closeInternal()
      throw new ChannelClosedError()
    }

    return eventId ?? ''
  }

  // ── Public channel object ─────────────────────────────────────────────────

  const channelObj: SSEChannel<TSignal> = {
    get state() {
      return state
    },
    connectionId,
    target,
    requestedTarget,
    stream,
    invalidate,
    close: closeInternal,
    disconnect: closeInternal,
    revoke(reason: string = 'revoked'): void {
      if (state === 'closed') return
      try {
        controller.enqueue(formatRevokeFrame(reason))
      } catch {
        // If the stream controller is already unusable, skip the frame and just close.
      }
      closeInternal()
    },
    onClose(callback: () => void): void {
      if (state === 'closed') {
        try { callback() } catch { /* ignore errors */ }
      } else {
        closeCallbacks.push(callback)
      }
    },
  }

  return channelObj
}

// ── Target signal validation ──────────────────────────────────────────────────

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null
}

export function validateSignalTargets(
  signal: unknown,
  targetConfig: SignalTarget | SignalTarget[]
): void {
  const signalList = Array.isArray(signal) ? signal : [signal]
  const declaredTargets = Array.isArray(targetConfig) ? targetConfig : [targetConfig]
  const declaredSet = new Set<string>(declaredTargets)
  const coveredTargets = new Set<string>()

  for (const s of signalList) {
    if (!isRecord(s)) {
      const sStr = typeof s === 'string' ? s : JSON.stringify(s)
      throw new Error(
        `[invalidate] Every signal must be an object. ` +
        `Got: ${sStr.slice(0, 200)}. ` +
        `Declared targets: [${declaredTargets.join(', ')}].`
      )
    }

    let targetStr = typeof s['target'] === 'string' ? s['target'] : ''

    if (targetStr === '') {
      if (declaredTargets.length === 1 && declaredTargets[0] !== undefined) {
        // Single-target channel: auto-fill target if omitted
        targetStr = declaredTargets[0]
        s['target'] = targetStr
      } else {
        const sStr = JSON.stringify(s)
        throw new Error(
          `[invalidate] Multi-target channel requires an explicit "target" field on every signal. ` +
          `Got signal without target: ${sStr.slice(0, 200)}. ` +
          `Declared targets: [${declaredTargets.join(', ')}].`
        )
      }
    }

    if (!declaredSet.has(targetStr)) {
      throw new Error(
        `[invalidate] Signal target "${targetStr}" is not in the channel's declared targets: ` +
        `[${declaredTargets.join(', ')}].`
      )
    }
    coveredTargets.add(targetStr)
  }

  if (declaredTargets.length > 1) {
    for (const t of declaredTargets) {
      if (!coveredTargets.has(t)) {
        throw new Error(
          `[invalidate] Multi-target channel requires signals for ALL declared targets. ` +
          `Missing target: "${t}". ` +
          `Declared: [${declaredTargets.join(', ')}], ` +
          `Provided: [${[...coveredTargets].join(', ')}].`
        )
      }
    }
  }
}
