import {
  isJSONValue,
  type InvalidateSignal,
  type ChannelState,
  type EventStore,
  type SignalTarget,
  type JSONValue,
  type TanStackQuerySignal,
  type SWRSignal,
  type RTKQuerySignal,
  type GenericInvalidateSignal,
  type LifetimeOptions,
  type BeforeFrameFn,
  type FrameGuardCtx,
  type FrameGuardResult,
} from '@/types/protocol.js'
import { type StandardSchemaV1, validateStandardSchema } from '@/types/standard-schema.js'
import { ChannelClosedError } from '@/types/errors.js'
import {
  formatInvalidateFrame,
  formatKeepalive,
  formatRevokeFrame,
  formatRetryFrame,
  formatRenewFrame,
} from '@/server/core/framing.js'
import { createEventStore } from '@/server/core/event-store.js'
import { PROTOCOL_CONSTANTS, SIGNAL_TARGETS, FRAME_GUARD_DEFAULTS } from '@/utils/constants.js'

/**
 * Configuration options for `createSSEChannel`.
 */
export interface SSEChannelOptions<TSignal extends InvalidateSignal = InvalidateSignal> {
  /** Target discriminator or target array for automatic signal tagging and multi-target fanout. Required unless provided via group channelDefaults. */
  target?: SignalTarget | SignalTarget[]
  /** Keepalive comment interval in milliseconds. Default: 0 (disabled). */
  keepaliveIntervalMs?: number
  /** Optional retry interval in milliseconds to send as a `retry: <ms>` frame on stream start. */
  retryIntervalMs?: number
  /** Optional Standard Schema for runtime signal validation. No schema = no validation. */
  signalSchema?: StandardSchemaV1<unknown, TSignal>
  /** Last event ID received from the client (e.g. from standard Last-Event-ID HTTP header). */
  lastEventId?: string
  /** Shared EventStore for recording history and replaying missed events upon reconnect. */
  eventStore?: EventStore
  /** Capacity of automatically instantiated EventStore if `eventStore` is not provided. */
  eventBufferCapacity?: number
  /** Custom ID generator for assigned event frames. Ignored if an external `eventStore` is provided. */
  idGenerator?: () => string
  /**
   * The unique connection ID generated by the client and sent as `__restale_cid__`.
   * Transport adapters (`attachSSE`, `toSSEResponse`) extract this from the request URL
   * and pass it here automatically.
   *
   * You may set this manually in tests or when calling `createSSEChannel` directly
   * without a transport adapter. In production code routed through a transport adapter,
   * the adapter always supplies this value — leave it unset.
   */
  connectionId?: string
  /**
   * The single target requested by the client, extracted from the `__restale_target__`
   * query parameter by transport adapters. When set, the channel will:
   * - Reject the connection immediately if the requested target is not in `options.target`.
   * - Filter outgoing frames to only emit signals matching this target.
   *
   * Accepts any string (not just known `SignalTarget` values) so that unrecognized
   * targets sent by the client are passed through and rejected by the unsupported-target
   * check rather than silently treated as "no preference".
   */
  requestedTarget?: string
  /**
   * A connection-level deadline after which the channel is closed.
   *
   * Express either as a relative duration from connection start (`ttlMs`) or as an
   * absolute epoch-ms timestamp (`deadline`). The two are mutually exclusive.
   *
   * When the deadline fires, `onDeadline` (default `'reconnect'`) controls whether the
   * channel sends a `renew` frame (asking the client to make one confirmatory reconnect
   * through the real auth middleware) or a terminal `revoke` frame.
   */
  lifetime?: LifetimeOptions
  /**
   * Integrator-supplied guard function called synchronously before each outgoing frame.
   *
   * By default it runs before **signal frames only**. Set `guardKeepalive: true` to also
   * run it before every keepalive tick (opt-in because keepalives are high-frequency).
   *
   * The function must be synchronous. Errors thrown inside it are the integrator's
   * responsibility — an unhandled throw is treated as `{ action: 'close' }`.
   */
  beforeFrame?: BeforeFrameFn<InvalidateSignal>
  /**
   * When `true`, `beforeFrame` also runs before every keepalive tick.
   * Has no effect if `beforeFrame` is not set. Default: `false`.
   */
  guardKeepalive?: boolean
}

/**
 * A server-side SSE channel that produces a `ReadableStream<Uint8Array>`.
 *
 * Runtime-agnostic — does not know about Node's `http` module or any specific
 * framework. Transport helpers (`restale-kit/node`, `restale-kit/fetch`) pipe
 * this stream into their runtime's response mechanism.
 */
export interface SSEChannel<TSignal extends InvalidateSignal = InvalidateSignal> {
  /** Current lifecycle state of the channel. */
  readonly state: ChannelState
  /**
   * The unique connection ID sent by the client (`__restale_cid__`).
   * Use this to register connection-level metadata and support targeted revocation
   * (e.g. close a specific tab's connection on logout).
   */
  readonly connectionId: string
  /** Configured target discriminator or target array. Required. */
  readonly target: SignalTarget | SignalTarget[]
  /** The single target requested by this client via query param, if any. May be an unrecognized string if the client sent an unknown target. */
  readonly requestedTarget: string | undefined
  /** The SSE byte stream to pipe into a response. */
  readonly stream: ReadableStream<Uint8Array>
  /**
   * Enqueue an invalidation signal (or batch) into the stream.
   *
   * - When `state` is `'closed'`: throws `ChannelClosedError`.
   * - When a `signalSchema` was provided and validation fails: throws `SchemaValidationError`.
   * - When a `signalSchema` returns a Promise: throws `SchemaValidationError` ("async schemas are not supported").
   *
   * Returns the event ID assigned to the invalidation frame.
   */
  invalidate(signal: TSignal | TSignal[] | InvalidateSignal | InvalidateSignal[], customId?: string): string
  /** Server-initiated close. Stops keepalive timer, closes the stream, transitions to `'closed'`. Idempotent. */
  close(): void
  /**
   * Called by a transport adapter when it detects the remote peer disconnected.
   * Same effect as `close()`. Idempotent.
   */
  disconnect(): void
  /**
   * Sends a terminal `revoke` SSE event frame to the client and then closes the channel.
   *
   * The client uses this event to distinguish an intentional server-initiated revocation
   * (logout, session expiry, security kick) from a transient network error, and will
   * NOT automatically reconnect. The resulting client status is `{ status: 'closed', reason: 'revoked' }`.
   *
   * Idempotent — if the channel is already closed, this is a no-op.
   *
   * @param reason - Human-readable reason string included in the event payload. Default: `'revoked'`.
   */
  revoke(reason?: string): void
  /**
   * Registers a one-shot callback invoked when the channel transitions to `'closed'`
   * (whether via `close()`, `disconnect()`, `revoke()`, or stream cancellation).
   * If the channel is already closed the callback fires synchronously.
   */
  onClose(callback: () => void): void
}

/**
 * Creates a new SSE channel.
 *
 * The channel produces a standard `ReadableStream<Uint8Array>` containing
 * SSE-formatted events and periodic keepalive comments. Transport adapters
 * pipe this stream into a response.
 */
export function createSSEChannel<TSignal extends InvalidateSignal = InvalidateSignal>(
  options: SSEChannelOptions<TSignal>
): SSEChannel<TSignal> {
  if (options.target === undefined) {
    throw new Error('[createSSEChannel] target is required.')
  }
  const keepaliveIntervalMs =
    options.keepaliveIntervalMs ?? PROTOCOL_CONSTANTS.DEFAULT_KEEPALIVE_INTERVAL_MS
  const retryIntervalMs = options.retryIntervalMs
  const signalSchema = options.signalSchema
  const lastEventId = options.lastEventId
  const idGenerator = options.idGenerator
  const connectionId = options.connectionId ?? ''
  const target = options.target
  const requestedTarget = options.requestedTarget
  const beforeFrame = options.beforeFrame
  const guardKeepalive = options.guardKeepalive ?? false
  // True if the client provided a Last-Event-ID header — i.e. this is a reconnect.
  const isResume = lastEventId !== undefined

  // Track whether this channel owns its eventStore (created internally) or was given an
  // external one. When the store is external (shared with a group), the group is responsible
  // for recording signals before calling invalidate() with a customId — the channel must not
  // call eventStore.add() a second time for the same event.
  const eventStore =
    options.eventStore ??
    (options.eventBufferCapacity !== undefined && options.eventBufferCapacity > 0
      ? createEventStore({ capacity: options.eventBufferCapacity, idGenerator })
      : undefined)
  const ownsEventStore = options.eventStore === undefined

  let state: ChannelState = 'open'
  let controller: ReadableStreamDefaultController<Uint8Array>
  let keepaliveTimer: ReturnType<typeof setInterval> | undefined
  let lifetimeTimer: ReturnType<typeof setTimeout> | undefined
  const closeCallbacks: Array<() => void> = []

  // ── Lifetime timer helpers ────────────────────────────────────────────────

  function resolveLifetimeMs(connectedAt: number): number | undefined {
    if (options.lifetime === undefined) return undefined
    const { ttlMs, deadline } = options.lifetime
    if (ttlMs !== undefined) return ttlMs
    if (deadline === undefined) return undefined // eslint-disable-line @typescript-eslint/no-unnecessary-condition -- runtime guard against malformed options or merged defaults
    return deadline - connectedAt
  }

  function scheduleLifetimeTimer(connectedAt: number): void {
    const rawDelayMs = resolveLifetimeMs(connectedAt)
    if (rawDelayMs === undefined) return

    // Apply jitter so connections sharing the same TTL don't all send renew simultaneously.
    const jitter = Math.random() * FRAME_GUARD_DEFAULTS.DEADLINE_JITTER_WINDOW_MS

    // Enforce the minimum-fire floor: even a deadline already in the past must not fire
    // immediately — it must wait at least DEADLINE_MIN_FIRE_DELAY_MS (spec §4.1.6).
    const fireDelayMs = Math.max(
      FRAME_GUARD_DEFAULTS.DEADLINE_MIN_FIRE_DELAY_MS,
      rawDelayMs + jitter
    )

    lifetimeTimer = setTimeout(() => {
      lifetimeTimer = undefined
      if (state !== 'open') return
      fireDeadline()
    }, fireDelayMs)
  }

  function fireDeadline(): void {
    if (state !== 'open') return

    const onDeadline = options.lifetime?.onDeadline ?? 'reconnect'

    if (onDeadline === 'revoke') {
      channelObj.revoke('deadline')
      return
    }

    // 'reconnect' (default) or object form — resolve maxAttempts / retryDelayMs.
    const maxAttempts =
      typeof onDeadline === 'object'
        ? (onDeadline.maxAttempts ?? FRAME_GUARD_DEFAULTS.RENEW_MAX_ATTEMPTS)
        : FRAME_GUARD_DEFAULTS.RENEW_MAX_ATTEMPTS
    const retryDelayMs =
      typeof onDeadline === 'object'
        ? (onDeadline.retryDelayMs ?? FRAME_GUARD_DEFAULTS.RENEW_RETRY_DELAY_MS)
        : FRAME_GUARD_DEFAULTS.RENEW_RETRY_DELAY_MS

    try {
      controller.enqueue(formatRenewFrame(maxAttempts, retryDelayMs))
    } catch {
      // controller already unusable — just close without the frame
    }
    closeInternal()
  }

  // ── Frame guard helper ────────────────────────────────────────────────────

  /**
   * Runs `beforeFrame` if it is configured for the given frame type.
   * Returns the result, or `{ action: 'send' }` when no guard is configured.
   * A thrown error inside `beforeFrame` is treated as `{ action: 'close' }` (spec §6).
   */
  function runGuard(ctx: FrameGuardCtx<TSignal>): FrameGuardResult {
    if (beforeFrame === undefined) return { action: 'send' }
    if (ctx.frameType === 'keepalive' && !guardKeepalive) return { action: 'send' }
    try {
      return beforeFrame(ctx)
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      console.warn(
        '[WARN][createSSEChannel] beforeFrame threw an unhandled error — treating as { action: \'close\' }.',
        '\n  error:', error.stack || error.message
      )
      return { action: 'close' }
    }
  }

  // ── Stream ────────────────────────────────────────────────────────────────

  const stream = new ReadableStream<Uint8Array>({
    start(ctrl) {
      controller = ctrl
      const connectedAt = Date.now()

      // Validate the requested target before doing anything else.
      // If it is unsupported or missing on a multi-target channel, emit a structured revoke frame and close immediately.
      const supportedTargets = Array.isArray(target) ? target : [target]
      if (requestedTarget === undefined && supportedTargets.length > 1) {
        const safeConnectionId = connectionId.replace(/\r\n|\r|\n/g, '\\n')
        console.warn(
          `[WARN][createSSEChannel] Rejected connection: no target requested for multi-target channel [${supportedTargets.join(', ')}]. connectionId: ${safeConnectionId}.`
        )
        try {
          controller.enqueue(
            formatRevokeFrame('unsupported-target', {
              requested: '',
              supported: supportedTargets,
            })
          )
        } catch {
          // controller unusable — just close
        }
        closeInternal()
        return
      }

      if (requestedTarget !== undefined) {
        // @ts-expect-error includes not present for SignalTarget type
        if (!supportedTargets.includes(requestedTarget)) {
          const safeRequestedTarget = requestedTarget.replace(/\r\n|\r|\n/g, '\\n')
          const safeConnectionId = connectionId.replace(/\r\n|\r|\n/g, '\\n')
          console.warn(
            `[WARN][createSSEChannel] Rejected connection: requested target "${safeRequestedTarget}" not in supported set [${supportedTargets.join(', ')}]. connectionId: ${safeConnectionId}.`
          )
          try {
            controller.enqueue(
              formatRevokeFrame('unsupported-target', {
                requested: requestedTarget,
                supported: supportedTargets,
              })
            )
          } catch {
            // controller unusable — just close
          }
          closeInternal()
          return
        }
      }

      if (retryIntervalMs !== undefined) {
        try {
          controller.enqueue(formatRetryFrame(retryIntervalMs))
        } catch {
          closeInternal()
          return
        }
      }

      // Replay missed historical events if lastEventId and eventStore are present
      if (lastEventId !== undefined && eventStore !== undefined) {
        try {
          const { events: missed, stale } = eventStore.getEventsAfter(lastEventId)
          if (stale) {
            // The cursor fell off the ring buffer or was never valid — the client missed
            // an unknown number of events. Send a full-invalidate signal (key: []) so the
            // client refetches everything rather than silently displaying stale data.
            // For a targeted client the stale full-invalidate is still valid: it carries
            // no explicit `target` field so processTargetSignals will stamp it with the
            // channel's configured target — which the client's adapter will handle.
            controller.enqueue(formatInvalidateFrame({ key: [] }))
          } else {
            for (const record of missed) {
              // Apply target transform during replay: the shared eventStore may store raw
              // (target-less) signals recorded by a group. processTargetSignals is safe to
              // call on already-tagged signals because hasTargetProperty passes them through.
              const replaySignal = processTargetSignals(record.signal, target)

              // Apply requestedTarget filter: skip signals that don't match this client's
              // requested target (same semantics as the live invalidate() filter path).
              if (requestedTarget !== undefined) {
                if (Array.isArray(replaySignal)) {
                  const filtered = replaySignal.filter((s) => {
                    const t = 'target' in s ? s.target : undefined
                    return t === requestedTarget
                  })
                  if (filtered.length === 0) continue
                  controller.enqueue(formatInvalidateFrame(filtered, record.id))
                  continue
                } else {
                  const t = 'target' in replaySignal ? replaySignal.target : undefined
                  if (t !== requestedTarget) continue
                }
              }

              controller.enqueue(formatInvalidateFrame(replaySignal, record.id))
            }
          }
        } catch {
          closeInternal()
          return
        }
      }

      if (keepaliveIntervalMs > 0) {
        keepaliveTimer = setInterval(() => {
          if (state !== 'open') return

          // Run the guard before every keepalive tick when guardKeepalive is enabled.
          if (beforeFrame !== undefined && guardKeepalive) {
            const ctx: FrameGuardCtx<InvalidateSignal> = {
              signal: undefined,
              frameType: 'keepalive',
              connectionId,
              requestedTarget,
              isResume,
            }
            const result = runGuard(ctx)
            if (result.action === 'skip') return
            if (result.action === 'close') {
              channelObj.revoke(result.reason)
              return
            }
          }

          try {
            controller.enqueue(formatKeepalive())
          } catch {
            closeInternal()
          }
        }, keepaliveIntervalMs)
      }

      scheduleLifetimeTimer(connectedAt)
    },
    cancel() {
      // Stream consumer cancelled — treat as disconnect
      closeInternal()
    },
  })

  // ── closeInternal ─────────────────────────────────────────────────────────

  function closeInternal(): void {
    if (state === 'closed') return
    state = 'closed'
    if (keepaliveTimer !== undefined) {
      clearInterval(keepaliveTimer)
      keepaliveTimer = undefined
    }
    if (lifetimeTimer !== undefined) {
      clearTimeout(lifetimeTimer)
      lifetimeTimer = undefined
    }
    try {
      controller.close()
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      // The stream controller closed status during cleanup
      console.warn(
        "[WARN][closeInternal] Controller close threw an expected error (likely already closed)",
        "\n  error:", error.stack || error.message
      )
    }
    // Fire one-shot close callbacks
    for (const cb of closeCallbacks) {
      try { cb() } catch { /* ignore errors in close callbacks */ }
    }
    closeCallbacks.length = 0
  }

  // ── invalidate ────────────────────────────────────────────────────────────

  function invalidate(
    signal: TSignal | TSignal[] | InvalidateSignal | InvalidateSignal[],
    customId?: string
  ): string {
    if (state === 'closed') {
      throw new ChannelClosedError()
    }

    const effectiveSignal = processTargetSignals(signal, target)

    // Filter by requestedTarget: drop signals that don't match the client's requested target.
    // This runs after processTargetSignals so signals are already target-stamped.
    if (requestedTarget !== undefined) {
      if (Array.isArray(effectiveSignal)) {
        const filtered = effectiveSignal.filter((s) => {
          const t = 'target' in s ? s.target : undefined
          const keep = t === requestedTarget
          return keep
        })
        if (filtered.length === 0) return ''
        // Re-assign and continue with the filtered batch
        return invalidateFiltered(filtered, customId)
      } else {
        const t = 'target' in effectiveSignal ? effectiveSignal.target : undefined
        if (t !== requestedTarget) {
          return ''
        }
      }
    }

    return invalidateFiltered(effectiveSignal, customId)
  }

  function invalidateFiltered(
    effectiveSignal: InvalidateSignal | InvalidateSignal[],
    customId?: string
  ): string {
    if (signalSchema) {
      const signals = Array.isArray(effectiveSignal) ? effectiveSignal : [effectiveSignal]
      for (const s of signals) {
        validateStandardSchema(s, signalSchema)
      }
    }

    // Run the frame guard before the signal frame is enqueued.
    if (beforeFrame !== undefined) {
      const ctx: FrameGuardCtx<TSignal> = {
        // @ts-expect-error am tired of fighting this error
        signal: effectiveSignal,
        frameType: 'signal',
        connectionId,
        requestedTarget,
        isResume,
      }
      const result = runGuard(ctx)
      if (result.action === 'skip') return ''
      if (result.action === 'close') {
        channelObj.revoke(result.reason)
        throw new ChannelClosedError()
      }
      // result.action === 'send' — fall through
    }

    let eventId = customId
    if (eventId === undefined && idGenerator !== undefined) {
      eventId = idGenerator()
    }

    if (eventStore !== undefined) {
      if (ownsEventStore || customId === undefined) {
        // Channel owns its store, or no id was provided — record it now.
        const record = eventStore.add(effectiveSignal, eventId)
        eventId = record.id
      } else {
        // External store with a customId provided: only skip add() when the record already
        // exists (i.e. the group pre-recorded it). If it is absent (standalone usage or an
        // unexpected call order), fall back to add() so the event is not silently lost.
        const { stale } = eventStore.getEventsAfter(customId)
        const alreadyRecorded = !stale
        if (!alreadyRecorded) {
          const record = eventStore.add(effectiveSignal, customId)
          eventId = record.id
        }
      }
    }

    try {
      controller.enqueue(formatInvalidateFrame(effectiveSignal, eventId))
    } catch {
      closeInternal()
      throw new ChannelClosedError()
    }

    return eventId ?? ''
  }

  // ── Public channel object ─────────────────────────────────────────────────

  const channelObj: SSEChannel<TSignal> = {
    get state() {
      return state
    },
    connectionId,
    target,
    requestedTarget,
    stream,
    invalidate,
    close: closeInternal,
    disconnect: closeInternal,
    revoke(reason: string = 'revoked'): void {
      if (state === 'closed') return
      try {
        controller.enqueue(formatRevokeFrame(reason))
      } catch {
        // If the stream controller is already unusable, skip the frame and just close.
      }
      closeInternal()
    },
    onClose(callback: () => void): void {
      if (state === 'closed') {
        try { callback() } catch { /* ignore errors */ }
      } else {
        closeCallbacks.push(callback)
      }
    },
  }

  return channelObj
}

// ── Target signal helpers ─────────────────────────────────────────────────────

function isRecord(val: unknown): val is Record<string, unknown> {
  return typeof val === 'object' && val !== null && !Array.isArray(val)
}

function hasTargetProperty(val: unknown): val is InvalidateSignal {
  return isRecord(val) && typeof val.target === 'string'
}

export function processTargetSignals<TSignal extends InvalidateSignal = InvalidateSignal>(
  signal: TSignal | TSignal[],
  targetConfig: SignalTarget | SignalTarget[]
): InvalidateSignal | InvalidateSignal[] {
  const signalList = Array.isArray(signal) ? signal : [signal]
  const targets = Array.isArray(targetConfig) ? targetConfig : [targetConfig]
  const result: InvalidateSignal[] = []

  for (const s of signalList) {
    if (hasTargetProperty(s)) {
      result.push(s)
      continue
    }

    const raw = isRecord(s) ? s : {}
    if (Array.isArray(targetConfig)) {
      for (const t of targets) {
        result.push(buildTargetSignal(raw, t))
      }
    } else {
      result.push(buildTargetSignal(raw, targetConfig))
    }
  }

  return !Array.isArray(signal) && result.length === 1 ? result[0] : result
}

function buildTargetSignal(raw: Record<string, unknown>, t: SignalTarget): InvalidateSignal {
  const keyVal = raw.queryKey ?? raw.key
  const key: JSONValue[] = Array.isArray(keyVal) ? keyVal.filter(isJSONValue) : []

  if (t === SIGNAL_TARGETS.TANSTACK) {
    const res: TanStackQuerySignal = { target: SIGNAL_TARGETS.TANSTACK, queryKey: key }
    if (typeof raw.exact === 'boolean') res.exact = raw.exact
    if (raw.type === 'active' || raw.type === 'inactive' || raw.type === 'all') res.type = raw.type
    if (raw.action === 'invalidate' || raw.action === 'refetch' || raw.action === 'reset' || raw.action === 'remove' || raw.action === 'cancel') {
      res.action = raw.action
    }
    if (typeof raw.stale === 'boolean') res.stale = raw.stale
    return res
  }

  if (t === SIGNAL_TARGETS.SWR) {
    const swrKey: string | JSONValue[] = typeof raw.key === 'string' ? raw.key : key
    const res: SWRSignal = { target: SIGNAL_TARGETS.SWR, key: swrKey }
    if (raw.action === 'revalidate' || raw.action === 'purge' || raw.action === 'remove') {
      res.action = raw.action
    }
    if (typeof raw.revalidate === 'boolean') res.revalidate = raw.revalidate
    if (raw.match === 'exact' || raw.match === 'prefix') res.match = raw.match
    return res
  }

  if (t === SIGNAL_TARGETS.RTK) {
    const rawTags = raw.tags
    const tags: RTKQuerySignal['tags'] = []
    if (Array.isArray(rawTags)) {
      for (const item of rawTags) {
        if (typeof item === 'string') {
          tags.push(item)
        } else if (isRecord(item) && typeof item.type === 'string') {
          const tagObj: { type: string; id?: string | number } = { type: item.type }
          if (typeof item.id === 'string' || typeof item.id === 'number') {
            tagObj.id = item.id
          }
          tags.push(tagObj)
        }
      }
    }
    return { target: SIGNAL_TARGETS.RTK, tags }
  }

  const res: GenericInvalidateSignal = { target: SIGNAL_TARGETS.GENERIC, key }
  if (typeof raw.exact === 'boolean') res.exact = raw.exact
  if (raw.action === 'invalidate' || raw.action === 'refetch' || raw.action === 'remove') {
    res.action = raw.action
  }
  return res
}
