import { describe, it, expect } from 'vitest'
import { SSEChannelGroup } from './channel-group.js'
import { createSSEChannel } from './channel.js'
import type { TanStackQuerySignal, SWRSignal, InvalidateSignal } from '../../types/protocol.js'

describe('SSEChannelGroup targeted contextual broadcast', () => {
  interface TestMeta {
    userId: string
  }

  interface TestContext {
    page: number
    sort: string
  }

  it('broadcasts signal generated by async signal function to matching connections', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const signals1: TanStackQuerySignal[] = []
    const channel1 = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-alice',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) signals1.push(...ctx.signal)
          else signals1.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channel1, { userId: 'alice' })
    await group.updateClientContext(channel1.connectionId, { page: 1, sort: 'price' })

    const signals2: TanStackQuerySignal[] = []
    const channel2 = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-bob',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) signals2.push(...ctx.signal)
          else signals2.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channel2, { userId: 'bob' })
    await group.updateClientContext(channel2.connectionId, { page: 2, sort: 'rating' })

    await group.broadcast({
      where: (meta, context) => context?.page === 1,
      signal: async (meta, context) => {
        return {
          queryKey: ['products', context?.page ?? 0],
          optimisticData: [{ id: 101, name: 'Item 1' }],
        }
      },
    })

    expect(signals1).toHaveLength(1)
    expect(signals1[0]).toEqual({
      target: 'tanstack-query',
      queryKey: ['products', 1],
      optimisticData: [{ id: 101, name: 'Item 1' }],
    })
    expect(signals2).toHaveLength(0)
  })

  it('skips channel delivery when signal generator returns null or undefined', async () => {
    const group = new SSEChannelGroup<SWRSignal, TestMeta, 'swr', TestContext>({
      target: 'swr',
    })

    const signals: SWRSignal[] = []
    const channel = createSSEChannel({
      target: 'swr',
      connectionId: 'conn-charlie',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) signals.push(...ctx.signal)
          else signals.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channel, { userId: 'charlie' })
    await group.updateClientContext(channel.connectionId, { page: 99, sort: 'newest' })

    await group.broadcast({
      signal: async (meta, context) => {
        if (context?.page === 99) return null
        return { key: ['todos'], optimisticData: ['todo1'] }
      },
    })

    expect(signals).toHaveLength(0)
  })

  // TEST: Predicate mismatch (where returns false)
  it('does not send any signal when predicate (where) evaluates to false', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const signals: TanStackQuerySignal[] = []
    const channel = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-no-match',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) signals.push(...ctx.signal)
          else signals.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channel, { userId: 'grace' })
    await group.updateClientContext(channel.connectionId, { page: 5, sort: 'price' })

    await group.broadcast({
      where: (meta, context) => context?.page === 1, // Grace is on page 5 -> mismatch
      signal: async (meta, context) => {
        return { queryKey: ['products', context?.page ?? 1], optimisticData: [] }
      },
    })

    expect(signals).toHaveLength(0)
  })

  // TEST: Stale context resolution and query key scoping
  it('uses registered server context and updates dynamically when updateClientContext is called', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const receivedSignals: TanStackQuerySignal[] = []
    const channel = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-stale-test',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) receivedSignals.push(...ctx.signal)
          else receivedSignals.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channel, { userId: 'henry' })
    // Step 1: Initial context on page 1
    await group.updateClientContext(channel.connectionId, { page: 1, sort: 'price' })

    // Broadcast 1: Server sends optimistic data for page 1
    await group.broadcast({
      signal: async (meta, context) => {
        return { queryKey: ['products', { page: context?.page ?? 1 }], optimisticData: [{ id: 1 }] }
      },
    })

    expect(receivedSignals).toHaveLength(1)
    expect(receivedSignals[0].queryKey).toEqual(['products', { page: 1 }])

    // Step 2: Client navigates to page 2 -> updateClientContext arrives at server
    await group.updateClientContext(channel.connectionId, { page: 2, sort: 'price' })

    // Broadcast 2: Server sends optimistic data for page 2
    await group.broadcast({
      signal: async (meta, context) => {
        return { queryKey: ['products', { page: context?.page ?? 2 }], optimisticData: [{ id: 2 }] }
      },
    })

    expect(receivedSignals).toHaveLength(2)
    expect(receivedSignals[1].queryKey).toEqual(['products', { page: 2 }])
  })

  // NEGATIVE TEST 1: Aggregates errors when signal generator throws for one connection
  it('throws AggregateError when signal generator fails for a connection while delivering to others', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const signalsAlice: TanStackQuerySignal[] = []
    const channelAlice = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-alice-err',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) signalsAlice.push(...ctx.signal)
          else signalsAlice.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channelAlice, { userId: 'alice' })
    await group.updateClientContext(channelAlice.connectionId, { page: 1, sort: 'price' })

    const channelError = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-err',
    })
    group.register(channelError, { userId: 'broken-user' })
    await group.updateClientContext(channelError.connectionId, { page: 1, sort: 'price' })

    await expect(
      group.broadcast({
        signal: async (meta) => {
          if (meta?.userId === 'broken-user') {
            throw new Error('Database query timeout for broken-user')
          }
          return { queryKey: ['products'], optimisticData: ['item1'] }
        },
      })
    ).rejects.toThrow(AggregateError)

    // Verify Alice still received her signal despite the error on broken-user
    expect(signalsAlice).toHaveLength(1)
  })

  // NEGATIVE TEST 2: Rejects invalid signal payload generated by signal function
  it('throws AggregateError when signal function returns invalid payload shape', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const channel = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-bad-payload',
    })
    group.register(channel, { userId: 'dave' })
    await group.updateClientContext(channel.connectionId, { page: 1, sort: 'price' })

    await expect(
      group.broadcast({
        signal: async () => {
          return 'invalid-non-object-signal' as unknown as TanStackQuerySignal
        },
      })
    ).rejects.toThrow(AggregateError)
  })

  // NEGATIVE TEST 3: Auto-deregisters channels that close while awaiting async signal resolution
  it('auto-deregisters channels that close during async signal resolution', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const channel = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-close-during-async',
    })
    group.register(channel, { userId: 'eve' })
    await group.updateClientContext(channel.connectionId, { page: 1, sort: 'price' })

    expect(group.getClientContext(channel.connectionId)).toEqual({ page: 1, sort: 'price' })

    await group.broadcast({
      signal: async () => {
        // Close channel while signal generator is awaiting
        channel.close()
        return { queryKey: ['products'], optimisticData: ['item'] }
      },
    })

    // Channel should be deregistered cleanly without throwing AggregateError
    expect(group.getClientContext(channel.connectionId)).toBeUndefined()
  })

  // NEGATIVE TEST 4: Rejects target mismatches in multi-target group
  it('throws AggregateError when signal function returns incompatible target in multi-target group', async () => {
    const group = new SSEChannelGroup<
      InvalidateSignal,
      TestMeta,
      ['tanstack-query', 'swr'],
      TestContext
    >({
      target: ['tanstack-query', 'swr'],
    })

    const channel = createSSEChannel({
      target: ['tanstack-query', 'swr'],
      requestedTarget: 'tanstack-query',
      connectionId: 'conn-multi-target',
    })
    group.register(channel, { userId: 'frank' })
    await group.updateClientContext(channel.connectionId, { page: 1, sort: 'price' })

    await expect(
      group.broadcast({
        signal: async () => {
          return { target: 'rtk-query', tags: ['todos'] } as unknown as InvalidateSignal
        },
      })
    ).rejects.toThrow(AggregateError)
  })
})
