import { describe, it, expect } from 'vitest'
import { SSEChannelGroup } from './channel-group.js'
import { createSSEChannel } from './channel.js'
import type { TanStackQuerySignal, SWRSignal, InvalidateSignal } from '../../types/protocol.js'
import { MemoryPubSubAdapter } from '../../test-fixtures/pubsub.js'

describe('SSEChannelGroup targeted contextual broadcast', () => {
  interface TestMeta {
    userId: string
  }

  interface TestContext {
    page: number
    sort: string
  }

  it('broadcasts signal generated by async signal function to matching connections', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const signals1: TanStackQuerySignal[] = []
    const channel1 = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-alice',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) signals1.push(...ctx.signal)
          else signals1.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channel1, { userId: 'alice' })
    await group.updateClientContext(channel1.connectionId, { page: 1, sort: 'price' }, { scope: { userId: 'alice' } })

    const signals2: TanStackQuerySignal[] = []
    const channel2 = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-bob',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) signals2.push(...ctx.signal)
          else signals2.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channel2, { userId: 'bob' })
    await group.updateClientContext(channel2.connectionId, { page: 2, sort: 'rating' }, { scope: { userId: 'bob' } })

    await group.broadcast({
      where: (meta, context) => context?.page === 1,
      signal: async (meta, context) => {
        return {
          queryKey: ['products', context?.page ?? 0],
          optimisticData: [{ id: 101, name: 'Item 1' }],
        }
      },
    })

    expect(signals1).toHaveLength(1)
    expect(signals1[0]).toEqual({
      target: 'tanstack-query',
      queryKey: ['products', 1],
      optimisticData: [{ id: 101, name: 'Item 1' }],
    })
    expect(signals2).toHaveLength(0)
  })

  it('skips channel delivery when signal generator returns null or undefined', async () => {
    const group = new SSEChannelGroup<SWRSignal, TestMeta, 'swr', TestContext>({
      target: 'swr',
    })

    const signals: SWRSignal[] = []
    const channel = createSSEChannel({
      target: 'swr',
      connectionId: 'conn-charlie',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) signals.push(...ctx.signal)
          else signals.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channel, { userId: 'charlie' })
    await group.updateClientContext(channel.connectionId, { page: 99, sort: 'newest' }, { scope: { userId: 'charlie' } })

    await group.broadcast({
      signal: async (meta, context) => {
        if (context?.page === 99) return null
        return { key: ['todos'], optimisticData: ['todo1'] }
      },
    })

    expect(signals).toHaveLength(0)
  })

  // TEST: Predicate mismatch (where returns false)
  it('does not send any signal when predicate (where) evaluates to false', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const signals: TanStackQuerySignal[] = []
    const channel = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-no-match',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) signals.push(...ctx.signal)
          else signals.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channel, { userId: 'grace' })
    await group.updateClientContext(channel.connectionId, { page: 5, sort: 'price' }, { scope: { userId: 'grace' } })

    await group.broadcast({
      where: (meta, context) => context?.page === 1, // Grace is on page 5 -> mismatch
      signal: async (meta, context) => {
        return { queryKey: ['products', context?.page ?? 1], optimisticData: [] }
      },
    })

    expect(signals).toHaveLength(0)
  })

  // TEST: Stale context resolution and query key scoping
  it('uses registered server context and updates dynamically when updateClientContext is called', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const receivedSignals: TanStackQuerySignal[] = []
    const channel = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-stale-test',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) receivedSignals.push(...ctx.signal)
          else receivedSignals.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channel, { userId: 'henry' })
    // Step 1: Initial context on page 1
    await group.updateClientContext(channel.connectionId, { page: 1, sort: 'price' }, { scope: { userId: 'henry' } })

    // Broadcast 1: Server sends optimistic data for page 1
    await group.broadcast({
      signal: async (meta, context) => {
        return { queryKey: ['products', { page: context?.page ?? 1 }], optimisticData: [{ id: 1 }] }
      },
    })

    expect(receivedSignals).toHaveLength(1)
    expect(receivedSignals[0].queryKey).toEqual(['products', { page: 1 }])

    // Step 2: Client navigates to page 2 -> updateClientContext arrives at server
    await group.updateClientContext(channel.connectionId, { page: 2, sort: 'price' }, { scope: { userId: 'henry' } })

    // Broadcast 2: Server sends optimistic data for page 2
    await group.broadcast({
      signal: async (meta, context) => {
        return { queryKey: ['products', { page: context?.page ?? 2 }], optimisticData: [{ id: 2 }] }
      },
    })

    expect(receivedSignals).toHaveLength(2)
    expect(receivedSignals[1].queryKey).toEqual(['products', { page: 2 }])
  })

  // NEGATIVE TEST 1: Aggregates errors when signal generator throws for one connection
  it('throws AggregateError when signal generator fails for a connection while delivering to others', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const signalsAlice: TanStackQuerySignal[] = []
    const channelAlice = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-alice-err',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) signalsAlice.push(...ctx.signal)
          else signalsAlice.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    group.register(channelAlice, { userId: 'alice' })
    await group.updateClientContext(channelAlice.connectionId, { page: 1, sort: 'price' }, { scope: { userId: 'alice' } })

    const channelError = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-err',
    })
    group.register(channelError, { userId: 'broken-user' })
    await group.updateClientContext(channelError.connectionId, { page: 1, sort: 'price' }, { scope: { userId: 'broken-user' } })

    await expect(
      group.broadcast({
        signal: async (meta) => {
          if (meta?.userId === 'broken-user') {
            throw new Error('Database query timeout for broken-user')
          }
          return { queryKey: ['products'], optimisticData: ['item1'] }
        },
      })
    ).rejects.toThrow(AggregateError)

    // Verify Alice still received her signal despite the error on broken-user
    expect(signalsAlice).toHaveLength(1)
  })

  // NEGATIVE TEST 2: Rejects invalid signal payload generated by signal function
  it('throws AggregateError when signal function returns invalid payload shape', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const channel = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-bad-payload',
    })
    group.register(channel, { userId: 'dave' })
    await group.updateClientContext(channel.connectionId, { page: 1, sort: 'price' }, { scope: { userId: 'dave' } })

    await expect(
      group.broadcast({
        signal: async () => {
          return 'invalid-non-object-signal' as unknown as TanStackQuerySignal
        },
      })
    ).rejects.toThrow(AggregateError)
  })

  // NEGATIVE TEST 3: Auto-deregisters channels that close while awaiting async signal resolution
  it('auto-deregisters channels that close during async signal resolution', async () => {
    const group = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
    })

    const channel = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-close-during-async',
    })
    group.register(channel, { userId: 'eve' })
    await group.updateClientContext(channel.connectionId, { page: 1, sort: 'price' }, { scope: { userId: 'eve' } })

    expect(group.getClientContext(channel.connectionId)).toEqual({ page: 1, sort: 'price' })

    await group.broadcast({
      signal: async () => {
        // Close channel while signal generator is awaiting
        channel.close()
        return { queryKey: ['products'], optimisticData: ['item'] }
      },
    })

    // Channel should be deregistered cleanly without throwing AggregateError
    expect(group.getClientContext(channel.connectionId)).toBeUndefined()
  })

  // NEGATIVE TEST 4: Rejects target mismatches in multi-target group
  it('throws AggregateError when signal function returns incompatible target in multi-target group', async () => {
    const group = new SSEChannelGroup<
      InvalidateSignal,
      TestMeta,
      ['tanstack-query', 'swr'],
      TestContext
    >({
      target: ['tanstack-query', 'swr'],
    })

    const channel = createSSEChannel({
      target: ['tanstack-query', 'swr'],
      requestedTarget: 'tanstack-query',
      connectionId: 'conn-multi-target',
    })
    group.register(channel, { userId: 'frank' })
    await group.updateClientContext(channel.connectionId, { page: 1, sort: 'price' }, { scope: { userId: 'frank' } })

    await expect(
      group.broadcast({
        signal: async () => {
          return { target: 'rtk-query', tags: ['todos'] } as unknown as InvalidateSignal
        },
      })
    ).rejects.toThrow(AggregateError)
  })

  // CLUSTER BROADCAST TEST 1: broadcastContextual(payload) across multi-node cluster over PubSub
  it('evaluates contextual generator across multiple server nodes when broadcastContextual is called', async () => {
    const pubsub = new MemoryPubSubAdapter<TanStackQuerySignal>()

    // Server Node 1 Group setup
    const groupNode1 = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
      pubsub,
      contextualSignal: async (payload: any, meta, context) => {
        if (context?.page !== undefined && context.page === payload?.page) {
          return { queryKey: ['products', context.page], optimisticData: [payload.item] }
        }
        return null
      },
    })

    // Server Node 2 Group setup
    const groupNode2 = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
      pubsub,
      contextualSignal: async (payload: any, meta, context) => {
        if (context?.page !== undefined && context.page === payload?.page) {
          return { queryKey: ['products', context.page], optimisticData: [payload.item] }
        }
        return null
      },
    })

    const node1Signals: TanStackQuerySignal[] = []
    const channelNode1 = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-node-1',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) node1Signals.push(...ctx.signal)
          else node1Signals.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    groupNode1.register(channelNode1, { userId: 'node-1-user' })
    await groupNode1.updateClientContext(channelNode1.connectionId, { page: 1, sort: 'price' }, { scope: { userId: 'node-1-user' } })

    const node2Signals: TanStackQuerySignal[] = []
    const channelNode2 = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-node-2',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) node2Signals.push(...ctx.signal)
          else node2Signals.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    groupNode2.register(channelNode2, { userId: 'node-2-user' })
    await groupNode2.updateClientContext(channelNode2.connectionId, { page: 1, sort: 'price' }, { scope: { userId: 'node-2-user' } })

    // Node 1 invokes broadcastContextual
    await groupNode1.broadcastContextual({ page: 1, item: 'cluster-product-101' })

    // Give microtasks time to deliver PubSub message across MemoryPubSubAdapter
    await new Promise((resolve) => setTimeout(resolve, 50))

    // Both Node 1 and Node 2 should have evaluated their local connections and delivered the signal!
    expect(node1Signals).toHaveLength(1)
    expect(node1Signals[0]).toEqual({
      target: 'tanstack-query',
      queryKey: ['products', 1],
      optimisticData: ['cluster-product-101'],
    })

    expect(node2Signals).toHaveLength(1)
    expect(node2Signals[0]).toEqual({
      target: 'tanstack-query',
      queryKey: ['products', 1],
      optimisticData: ['cluster-product-101'],
    })
  })

  // CLUSTER BROADCAST TEST 2: Named contextual handler execution across cluster
  it('executes registered named contextual handler across multi-node cluster over PubSub', async () => {
    const pubsub = new MemoryPubSubAdapter<TanStackQuerySignal>()

    const handler = {
      where: (payload: any, meta: any, context: any) => context?.sort === payload?.sort,
      signal: async (payload: any, meta: any, context: any) => ({
        queryKey: ['sorted-products', payload.sort],
        optimisticData: [payload.title],
      }),
    }

    const groupNode1 = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
      pubsub,
    })
    groupNode1.registerContextualHandler('sorted-update', handler)

    const groupNode2 = new SSEChannelGroup<TanStackQuerySignal, TestMeta, 'tanstack-query', TestContext>({
      target: 'tanstack-query',
      pubsub,
    })
    groupNode2.registerContextualHandler('sorted-update', handler)

    const node2Signals: TanStackQuerySignal[] = []
    const channelNode2 = createSSEChannel({
      target: 'tanstack-query',
      connectionId: 'conn-node-2-named',
      beforeFrame: (ctx) => {
        if (ctx.frameType === 'signal') {
          if (Array.isArray(ctx.signal)) node2Signals.push(...ctx.signal)
          else node2Signals.push(ctx.signal)
        }
        return { action: 'send' }
      },
    })
    groupNode2.register(channelNode2, { userId: 'user-node-2' })
    await groupNode2.updateClientContext(channelNode2.connectionId, { page: 1, sort: 'price' }, { scope: { userId: 'user-node-2' } })

    // Node 1 triggers named broadcast
    await groupNode1.broadcastContextual('sorted-update', { sort: 'price', title: 'Cheapest Item' })

    await new Promise((resolve) => setTimeout(resolve, 50))

    expect(node2Signals).toHaveLength(1)
    expect(node2Signals[0]).toEqual({
      target: 'tanstack-query',
      queryKey: ['sorted-products', 'price'],
      optimisticData: ['Cheapest Item'],
    })
  })
})
